export const UPDATE_TREE = 'UPDATE_TREE';
export const START_WALK_TREE = 'START_WALK_TREE';
export const SUCCESS_WALK_TREE = 'SUCCESS_WALK_TREE';
export const ERROR_WALK_TREE = 'ERROR_WALK_TREE';
export const SET_MIN_SIZE = 'SET_MIN_SIZE';
